[GRIDMET]
GRIDMET_PARAMS = ['pr', 'tmmn', 'tmmx']
GRIDMET_BOUNDS = [-124.787500, 25.045833, -67.037500, 49.420833]
GRIDMET_NROWS = 585
GRIDMET_NCOLS = 1386
GRIDMET_XRES = 0.041666666666666664
GRIDMET_YRES = 0.04166666666666668

[MWB_FLOW]
INPUT_VARS = ['mo_precip','mo_temp', 'mo_dischg']
DSET_COORDS = ['location', 'time', 'lat']